### ISSUE TITLE
gym rewards

### ISSUE THREAD

**Issue by snyperc** [SmashMC-Development/Suggestions#535] opened 2021-06-13 15:37 UTC
I think we should get more for beating gym leaders. When npchouse is on we literally get 10x better loot than what we get from gyms and theyre way easier. Cus like we are actually against good players and im pretty ure all we get is 10k. Its kinda underwhelming and noone really needs to go for gym battles, which kinda takes away the whole point of them in the first place

**Which servers does this apply to?**
pixelmon

**Comment by Rasgnarok** [comment] 2021-06-16 18:21
Closing, duplicate of https://github.com/SmashMC-Development/Suggestions/issues/535

**Closed as completed** 2021-06-16 18:21 UTC
Labels: discussion needed, aqua plugin, pixelmon servers, accepted
