### ISSUE TITLE
Add: creeper heads, enchanted golden apples and skeleton skulls to the NPC's in /warp mart.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#274] opened 2021-05-08 15:50 UTC
**Describe the suggestion**
Add creeper heads, enchanted golden apples and skeleton skulls to /warp mart, so that people who make banners can still do this.

**Which servers does this apply to?**
Network.

**Comment by HackuJacku** [comment] 2021-06-01 09:14
Which server(s) is this for please?

**Comment by Rasgnarok** [comment] 2021-06-09 01:51
Forwarded to main tracker, duplicate of #319.

**Closed by Rasgnarok** 2021-06-09 01:51 UTC
Labels: discussion needed, pixelmon servers, survival server
