### ISSUE TITLE
Ability to undo /unbreedable

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#961] opened 2022-04-03 22:34 UTC
**Describe the suggestion**
If possible can we bring back the ability to undo /breedable. I found it helpful being able to make a pokemon breedable after setting it to unbreedable. When most players make a pokemon unbreedable they intend that it will sell in gts, however not all pokemons sell. It would be handy to instead breed with it rather than having a non-selling pokemon in our pc taking up space. 

**Which servers does this apply to?**
I would like this to be on Rayquaza but will most likely affect all servers if it comes to play. 

**Additional context**
N/A

**Comment by Mikirae** [comment] 2022-04-07 08:34
We had a whole discussion amongst ourselves and completely got rid of the /breedable command. There were a ton of ways to abuse it and glitched caused by it iirc. There were some more reasons but its 3:33 am and I don’t remember. 
But, since we had a whole discussion on it already, I’m going to close this, but thank you for suggesting :)

**Closed as completed by Mikirae** 2022-04-07 08:34 UTC
