### ISSUE TITLE
battling in warzone

### ISSUE THREAD

**Issue by BigChungv2** [SmashMC-Development/Suggestions#901] opened 2022-01-29 20:07 UTC
**Describe the suggestion**
Revert back to the battling warzone style instead of giving people the chance to choose teams

**Which servers does this apply to?**
all

**Additional context**
a lot of times battling in warzone with people who don't want to have a pokemon stole from them either pretend to of crashed or just disconnect from the server when you try to battle them, and I've had it recently where the person has come back on and I've mentioned it to them and they just log off the moment you try to tell them its wrong and to come back to rebattle, reverting back to the pre-reset warzone battles would prevent this because it used to punish people who were disconnecting by just letting the other person steal a pokemon anyway.

**Comment by Mikirae** [comment] 2022-01-31 07:00
This is something that's being worked on currently :)
Closing as it's a duplicate of other tickets.
Thank you for the suggestion, though!

**Closed as completed by Mikirae** 2022-01-31 07:00 UTC
